define(['cdf/Base',
  'cdf/Dashboards',
  'cdf/jquery',
  'cdf/jquery.ui',
  'cdf/jquery-impromptu.3.1',
  'cdf/jquery.bgiframe',
  'cdf/jquery.blockUI',
  'cdf/jquery.corner',
  'cdf/jquery.eventstack',
  'cdf/jquery.i18n.properties',
  'cdf/jquery.jdMenu',
  'cdf/jquery.positionBy',
  'cdf/jquery.sparkline',
  'cdf/jquery.tooltip',
  'cdf/json',
  'cdf/simile/ajax/simile-ajax-api',
  'cdf/simile/ajax/scripts/json',
  'cdf/CoreComponents'], function(){
	
});